#!/bin/sh

# place in your Firmware folder

source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/posix_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)/Tools/sitl_gazebo


export PX4_HOME_LAT=55.471979
export PX4_HOME_LON=10.414697
#export PX4_HOME_LAT=55.481202
#export PX4_HOME_LON=10.344599
